# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('aggregate_status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='received', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['aggregate_status', 'created_at'], name='hmi_robot_order_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='RobotOrderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=120)),
                ('option', models.IntegerField(default=0)),
                ('qty_index', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('received', 'Antri'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='received', max_length=20)),
                ('assigned_stirrer', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('plc_seen_on', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hmi.robotorder')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'assigned_stirrer'], name='hmi_robot_task_state_idx'), models.Index(fields=['created_at', 'id'], name='hmi_robot_task_queue_idx')],
            },
        ),
    ]
