"""
Django settings for Kuali project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config 

# =========================
# PROJECT PATHS
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SECURITY / DEBUG CONFIG
# =========================
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-local-development-key-change-me'
)

DEBUG_VALUE = str(config('DEBUG', default='True')).strip().lower()
DEBUG = DEBUG_VALUE not in ['0', 'false', 'no', 'off', 'release', 'prod', 'production']


def parse_csv(value):
    return [item.strip() for item in str(value or '').split(',') if item.strip()]


def origins_from_hosts(hosts):
    origins = []
    for host in hosts:
        if not host or host == '*':
            continue
        normalized_host = host.rstrip('/')
        if '://' in normalized_host:
            origins.append(normalized_host)
        else:
            origins.extend([
                f'http://{normalized_host}',
                f'https://{normalized_host}',
            ])
    return origins


# =========================
# HOSTS / ORIGIN CONFIG
# =========================
HOST = config('HOST', default='').strip()
HOSTS = parse_csv(config('HOSTS', default=HOST or '127.0.0.1'))
ALLOWED_HOSTS = list(dict.fromkeys([
    *HOSTS,
    'localhost',
    '127.0.0.1',
]))

# =========================
# SUBPATH / REVERSE PROXY CONFIG
# =========================
FORCE_SCRIPT_NAME = config('FORCE_SCRIPT_NAME', default='/Kuali').strip()
if FORCE_SCRIPT_NAME in ['', '/']:
    FORCE_SCRIPT_NAME = None
elif not FORCE_SCRIPT_NAME.startswith('/'):
    FORCE_SCRIPT_NAME = f'/{FORCE_SCRIPT_NAME}'

PUBLIC_ORIGIN = config('PUBLIC_ORIGIN', default='').strip()
PUBLIC_ORIGINS = origins_from_hosts(parse_csv(PUBLIC_ORIGIN))
HOST_ORIGINS = origins_from_hosts(ALLOWED_HOSTS)
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([*HOST_ORIGINS, *PUBLIC_ORIGINS]))
SECURE_COOKIE_DEFAULT = (not DEBUG) and any(
    origin.startswith('https://') for origin in PUBLIC_ORIGINS
)

# =========================
# FORWARDED HEADER CONFIG
# =========================
USE_X_FORWARDED_HOST = config('USE_X_FORWARDED_HOST', default=True, cast=bool)
USE_X_FORWARDED_PORT = config('USE_X_FORWARDED_PORT', default=True, cast=bool)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# =========================
# SESSION / CSRF COOKIE CONFIG
# =========================
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_NAME = config('SESSION_COOKIE_NAME', default='kuali_sessionid')
SESSION_COOKIE_AGE = 60 * 60 * 24 * 365
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_PATH = FORCE_SCRIPT_NAME or '/'
SESSION_EXPIRE_AT_BROWSER_CLOSE = config('SESSION_EXPIRE_AT_BROWSER_CLOSE', default=False, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=SECURE_COOKIE_DEFAULT, cast=bool)

CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_PATH = FORCE_SCRIPT_NAME or '/'
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=SECURE_COOKIE_DEFAULT, cast=bool)

# =========================
# DJANGO APPS / MIDDLEWARE CONFIG
# =========================
INSTALLED_APPS = [
    'daphne',    # Must be before staticfiles
    'channels',  # Must be before staticfiles
    'django.contrib.humanize',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hmi',
    'corsheaders',
    'background_task',
    'rest_framework',
]

ASGI_APPLICATION = 'projects.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'projects.urls'


# =========================
# AUTH / TEMPLATE CONFIG
# =========================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'hmi'
LOGOUT_REDIRECT_URL = 'login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projects.wsgi.application'


# =========================
# CHANNELS / REDIS CONFIG
# =========================
REDIS_CACHE_URL = config('REDIS_CACHE_URL', default='')
REDIS_CHANNEL_URL = config('REDIS_CHANNEL_URL', default='')
REDIS_CHANNEL_PREFIX = config('REDIS_CHANNEL_PREFIX', default='')
USE_REDIS_CHANNELS = config('USE_REDIS_CHANNELS', default=False, cast=bool)
USE_REDIS_CACHE = config('USE_REDIS_CACHE', default=False, cast=bool)

if USE_REDIS_CHANNELS and REDIS_CHANNEL_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_CHANNEL_URL],
                'prefix': REDIS_CHANNEL_PREFIX,
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

if USE_REDIS_CACHE and REDIS_CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_CACHE_URL,
            'KEY_PREFIX': REDIS_CACHE_PREFIX,
        }
    }

# =========================
# DATABASE CONFIG
# =========================
DB_NAME = config('DB_NAME', default='')

if DB_NAME:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': DB_NAME,
            'USER': config('DB_USER', default=''),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default=''),
            'PORT': config('DB_PORT', default='3306', cast=int),
        },
        'sqlite_db': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        },
        'sqlite_db': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# =========================
# PASSWORD VALIDATION CONFIG
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================
# LOCALIZATION / TIMEZONE CONFIG
# =========================
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = False


# =========================
# STATIC / MEDIA FILE CONFIG
# =========================
URL_PREFIX = FORCE_SCRIPT_NAME or ''
STATIC_URL = f'{URL_PREFIX}/static/' if URL_PREFIX else '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = []
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = f'{URL_PREFIX}/media/' if URL_PREFIX else '/media/'
MEDIA_ROOT = config('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

# =========================
# DEFAULT MODEL FIELD CONFIG
# =========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================
# CORS CONFIG
# =========================
CORS_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS
CORS_ALLOW_CREDENTIALS = True

# =========================
# EMAIL / OTP CONFIG
# =========================
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default=EMAIL_HOST_USER or 'noreply@kuali.local'
)
OTP_EMAIL_METHOD = config('OTP_EMAIL_METHOD', default='console')

# =========================
# MQTT BROKER CONFIG
# =========================
MQTT_ENABLED    = config('MQTT_ENABLED',    default=False,       cast=bool)
MQTT_BROKER     = config('MQTT_BROKER',     default='localhost')
MQTT_PORT       = config('MQTT_PORT',       default=1883,        cast=int)
MQTT_USERNAME   = config('MQTT_USERNAME',   default='')
MQTT_PASSWORD   = config('MQTT_PASSWORD',   default='')
MQTT_CLIENT_ID  = config('MQTT_CLIENT_ID',  default='kuali-hmi')
MQTT_TOPIC_ROOT = config('MQTT_TOPIC_ROOT', default='kuali')
MQTT_ORDER_COMMAND_TOPIC = config('MQTT_ORDER_COMMAND_TOPIC', default='order/cmd/#')
MQTT_ORDER_STATUS_DEVICE = config('MQTT_ORDER_STATUS_DEVICE', default='kuali')

# =========================
# PLC / MODBUS CONFIG
# =========================
PLC_ENABLED      = config('PLC_ENABLED',      default=False,       cast=bool)
MODBUS_MODE      = config('MODBUS_MODE',      default='simulator')  # 'rtu' | 'tcp' | 'simulator'
MODBUS_AUTO_CONNECT = config('MODBUS_AUTO_CONNECT', default=True, cast=bool)
MODBUS_AUTO_DISCONNECT = config('MODBUS_AUTO_DISCONNECT', default=False, cast=bool)
SERIAL_PORT      = config('SERIAL_PORT',      default='/dev/ttyUSB0')
SERIAL_BAUDRATE  = config('SERIAL_BAUDRATE',  default=9600,        cast=int)
SERIAL_PARITY    = config('SERIAL_PARITY',    default='N')          # 'N' | 'E' | 'O'
SERIAL_STOPBITS  = config('SERIAL_STOPBITS',  default=1,           cast=int)
SERIAL_BYTESIZE  = config('SERIAL_BYTESIZE',  default=8,           cast=int)
SERIAL_TIMEOUT   = config('SERIAL_TIMEOUT',   default=5,           cast=float)
PLC_TCP_HOST     = config('PLC_TCP_HOST',     default='192.168.1.10')
PLC_TCP_PORT     = config('PLC_TCP_PORT',     default=502,         cast=int)
PLC_POLL_INTERVAL_MS = config('PLC_POLL_INTERVAL_MS', default=500, cast=int)

# =========================
# UPLOAD LIMIT CONFIG
# =========================
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
